GANA2.0/gana/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

GANA2.0/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [       
    path('',                           views.index,   name='index'),
    path('<int:question_id>/',         views.detail,  name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/',    views.vote,    name='vote'),
]

print(urlpatterns)

GANA2.0/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text    

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)         

class Choice(models.Model):
    #Relationship defined: 1-1 Each choice is related to a
    # single question (Available: n-1, n-n, 1-1)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

GANA2.0/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import loader
from .models import Question

def index(request):
    lastest_questions_lst = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': lastest_questions_lst}
          # render(request object, template name, optional dictionary)
          # Returns an HttpResponse object of the given template rendered
          # with the given context.
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    # The get_object_or_404() function takes a Django model as its
    # first argument and an arbitrary number of keyword arguments,
    # which it passes to the get() function of the model’s manager
    # get_list_or_404() uses filter()
    question = get_object_or_404(Question,pk=question_id)

    return render(request, "polls/detail.html", {'question': question})

def results(request, question_id):
    return HttpResponse("You're looking at the results of question %s." % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)    

GANA2.0/polls/templates/polls/detail.html
<h1> {{question.question_text}}</h1>

{% if error_message %}<p><strong>{{ error_message}}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id%}" method="post">
{% csrf_token%}
{% for choice in question.choice_set.all %}
    <input type='radio' name='choice' id='choice{{ forloop.couter}}' value='{{ choice.id}}'>
    <label for='choice{{ forloop.counter}}'>{{ choice.choice_text}}</label><br>
{% endfor %}

<input type='submit' value='VOTE'>
</form>

GANA2.0/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
                        <!-- url App_name:path_name in "polls/urls" file-->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}